// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sspAssignment3.Models;

namespace sspAssignment3.Migrations
{
    [DbContext(typeof(NurseDbContext))]
    [Migration("20210524141142_name")]
    partial class name
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("sspAssignment3.Models.Nurse", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Section")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Nurses");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "DefaultNurse1@gmail.com",
                            Name = "DefaultNurse1",
                            Section = 0
                        },
                        new
                        {
                            ID = 2,
                            Email = "DefaultNurse2@hotmail.com",
                            Name = "DefaultNurse2",
                            Section = 1
                        },
                        new
                        {
                            ID = 3,
                            Email = "DefaultNurse3@yahoo.com",
                            Name = "DefaultNurse3",
                            Section = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
